version: "3.4"
services:
  mysql:
    build: ../../tools/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=sample_database
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  redis:
    image: redis:3.2.4-alpine
    restart: always
    ports:
      - 6379:6379

  api-server:
    restart: always
    build: ../../apiServer
    ports:
      - 18080:18080
    environment:
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis

  jupyter:
    restart: always
    build: ../../tools/jupyter
    ports:
      - 8888:8888
    volumes:
      - ./volume/jupyter:/opt/python/jupyter
      - ./volume/jupyterlab:/opt/python/jupyterlab
      - ./volume/library:/opt/python/library

  prometheus:
    image: prom/prometheus
    volumes:
      - ../../tools/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    volumes:
      - ../../tools/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ../../tools/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ../../tools/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=View Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    depends_on:
      - prometheus
