name: GCE Environment Use Terraform

on:
  push:
    branches: [ destroy ]

jobs:
  apply-environment:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      TF_VAR_GOOGLE_SERVICE_KEY: ${{ secrets.GOOGLE_SERVICE_KEY }}
      TF_VAR_GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      TF_VAR_GOOGLE_COMPUTE_REGION: ${{ secrets.GOOGLE_COMPUTE_REGION }} # "asia-northeast1"
      TF_VAR_GOOGLE_COMPUTE_ZONE: ${{ secrets.GOOGLE_COMPUTE_ZONE }} # "asia-northeast1-a"
      TF_VAR_GOOGLE_CREDENTIALS_JSON_PATH: ./account.json
      TF_VAR_SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_KEY_PUB: ${{ secrets.SSH_KEY_PUB }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: apply
        working-directory: ./terraform/gce
        run: |
          terraform init
          sh import.sh
          sh destroy.sh
